feeds:
  - type: article
    url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
    source: The New York Times
    region: USA
  
  - type: article
    url: https://techcrunch.com/feed/
    source: TechCrunch
    region: USA
  
  - type: podcast
    url: https://feeds.simplecast.com/qdSzqZ5Q
    source: Simplecast Test
    region: Global
