# sources.yaml
# type: article | video | podcast | book | event
# region: global | us | uk | jp | ...

sources:
  # --- Artículos / Revistas / Blogs (estables) ---
  - name: "The Whiskey Wash"
    url: "https://thewhiskeywash.com/feed/"
    type: "article"
    region: "global"

  - name: "WhiskyNotes"
    url: "https://whiskynotes.be/feed"
    type: "article"
    region: "global"

  - name: "Master of Malt Blog"
    url: "https://www.masterofmalt.com/blog/feed/"
    type: "article"
    region: "uk"

  - name: "The Whiskey Reviewer"
    url: "https://whiskeyreviewer.com/feed/"
    type: "article"
    region: "global"

  - name: "Bourbon & Banter"
    url: "https://bourbonbanter.com/feed/"
    type: "article"
    region: "us"

  - name: "Whiskyfun"
    url: "https://whiskyfun.com/whatsnew.xml"
    type: "article"
    region: "global"

  - name: "Reddit r/Scotch"
    url: "https://www.reddit.com/r/Scotch/.rss"
    type: "article"
    region: "global"

  # --- Podcasts (RSS estables) ---
  - name: "WhiskyCast (Podcast)"
    url: "https://whiskycast.libsyn.com/rss"
    type: "podcast"
    region: "global"

  - name: "Bourbon Pursuit (Podcast)"
    url: "https://bourbonpursuit.libsyn.com/rss"
    type: "podcast"
    region: "us"

  - name: "This Week in Bourbon (Podcast)"
    url: "https://thisweekinbourbon.libsyn.com/rss"
    type: "podcast"
    region: "us"

  - name: "SMWS – Whisky Talk (Podcast)"
    url: "https://feeds.buzzsprout.com/650835.rss"
    type: "podcast"
    region: "uk"
