name: Build & Publish Whisky Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"   # se ejecuta cada 2 horas

permissions:
  contents: write

# Evita carreras (si lanzas otro build, cancela el anterior)
concurrency:
  group: whisky-news-feed
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i

      - name: Build feed.json
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}   # clave guardada en Settings → Secrets and variables → Actions
        run: npm run build

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add feed.json
        run: |
          git add docs/feed.json
          git status --porcelain

      - name: Commit (skip if no changes)
        run: |
          git commit -m "chore: update feed.json [skip ci]" || echo "Sin cambios"

      - name: Rebase with remote main (avoid non-fast-forward)
        run: |
          git fetch origin main
          git pull --rebase origin main || true

      - name: Push
        run: |
          git push origin HEAD:main
