name: Build & Publish Whisky Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build feed
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: npm run build

      # Si el script salió con 1 por feed vacío, este paso no corre (success() requerido)
      - name: Commit & Publish feed
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/feed.json
          git commit -m "chore: update feed.json [skip ci]" || echo "No changes"
          git pull --rebase
          git push
